# Generated by Django 4.1 on 2022-08-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, default='unknown.png', upload_to='notes-pics'),
        ),
    ]
